-- Insert data for 100 subjects
INSERT INTO Subject (Exam, Syllabus, Projects) VALUES
('Math 101', 'Algebra', 'Project A'),
('Physics 101', 'Mechanics', 'Project B'),
('Chemistry 101', 'Chemical Bonding', 'Project C'),
('Biology 101', 'Cell Biology', 'Project D'),
('Computer Science 101', 'Programming Fundamentals', 'Project E'),
('English Literature 101', 'Shakespearean Literature', 'Project F'),
('History 101', 'Ancient Civilizations', 'Project G'),
('Geography 101', 'Physical Geography', 'Project H'),
('Economics 101', 'Microeconomics', 'Project I'),
('Political Science 101', 'Introduction to Political Theory', 'Project J'),
('Psychology 101', 'Introduction to Psychology', 'Project K'),
('Sociology 101', 'Introduction to Sociology', 'Project L'),
('Anthropology 101', 'Cultural Anthropology', 'Project M'),
('Archeology 101', 'Introduction to Archeology', 'Project N'),
('Art History 101', 'Renaissance Art', 'Project O'),
('Music Theory 101', 'Introduction to Music Theory', 'Project P'),
('Philosophy 101', 'Introduction to Philosophy', 'Project Q'),
('Statistics 101', 'Introduction to Statistics', 'Project R'),
('Algebra 102', 'Linear Algebra', 'Project S'),
('Physics 102', 'Electromagnetism', 'Project T'),
('Chemistry 102', 'Organic Chemistry', 'Project U'),
('Biology 102', 'Genetics', 'Project V'),
('Computer Science 102', 'Data Structures and Algorithms', 'Project W'),
('English Literature 102', 'Modern Literature', 'Project X'),
('History 102', 'World War I and II', 'Project Y'),
('Geography 102', 'Human Geography', 'Project Z'),
('Economics 102', 'Macroeconomics', 'Project AA'),
('Political Science 102', 'Comparative Politics', 'Project AB'),
('Psychology 102', 'Cognitive Psychology', 'Project AC'),
('Sociology 102', 'Social Theory', 'Project AD'),
('Anthropology 102', 'Biological Anthropology', 'Project AE'),
('Archeology 102', 'Historical Archeology', 'Project AF'),
('Art History 102', 'Modern Art', 'Project AG'),
('Music Theory 102', 'Harmony and Counterpoint', 'Project AH'),
('Philosophy 102', 'Ethics', 'Project AI'),
('Statistics 102', 'Regression Analysis', 'Project AJ'),
('Algebra 103', 'Abstract Algebra', 'Project AK'),
('Physics 103', 'Quantum Mechanics', 'Project AL'),
('Chemistry 103', 'Physical Chemistry', 'Project AM'),
('Biology 103', 'Ecology', 'Project AN'),
('Computer Science 103', 'Operating Systems', 'Project AO'),
('English Literature 103', 'Postcolonial Literature', 'Project AP'),
('History 103', 'Cold War History', 'Project AQ'),
('Geography 103', 'Cartography', 'Project AR'),
('Economics 103', 'Development Economics', 'Project AS'),
('Political Science 103', 'International Relations', 'Project AT'),
('Psychology 103', 'Developmental Psychology', 'Project AU'),
('Sociology 103', 'Criminology', 'Project AV'),
('Anthropology 103', 'Linguistic Anthropology', 'Project AW'),
('Archeology 103', 'Archaeological Theory', 'Project AX'),
('Art History 103', 'Asian Art', 'Project AY'),
('Music Theory 103', 'Music Composition', 'Project AZ'),
('Philosophy 103', 'Metaphysics', 'Project BA'),
('Statistics 103', 'Time Series Analysis', 'Project BB'),
('Algebra 104', 'Number Theory', 'Project BC'),
('Physics 104', 'Astrophysics', 'Project BD'),
('Chemistry 104', 'Inorganic Chemistry', 'Project BE'),
('Biology 104', 'Evolutionary Biology', 'Project BF'),
('Computer Science 104', 'Computer Networks', 'Project BG'),
('English Literature 104', 'American Literature', 'Project BH'),
('History 104', 'Medieval History', 'Project BI'),
('Geography 104', 'Geographic Information Systems', 'Project BJ'),
('Economics 104', 'Behavioral Economics', 'Project BK'),
('Political Science 104', 'Public Administration', 'Project BL'),
('Psychology 104', 'Abnormal Psychology', 'Project BM'),
('Sociology 104', 'Globalization', 'Project BN'),
('Anthropology 104', 'Archaeological Methods', 'Project BO'),
('Archeology 104', 'Prehistoric Archaeology', 'Project BP'),
('Art History 104', 'African Art', 'Project BQ'),
('Music Theory 104', 'Music History', 'Project BR'),
('Philosophy 104', 'Philosophy of Mind', 'Project BS'),
('Statistics 104', 'Design of Experiments', 'Project BT'),
('Algebra 105', 'Group Theory', 'Project BU'),
('Physics 105', 'Nuclear Physics', 'Project BV'),
('Chemistry 105', 'Analytical Chemistry', 'Project BW'),
('Biology 105', 'Cellular Biology', 'Project BX'),
('Computer Science 105', 'Database Management Systems', 'Project BY'),
('English Literature 105', 'British Literature', 'Project BZ'),
('History 105', 'Ancient History', 'Project CA'),
('Geography 105', 'Urban Geography', 'Project CB'),
('Economics 105', 'Game Theory', 'Project CC'),
('Political Science 105', 'Political Philosophy', 'Project CD'),
('Psychology 105', 'Social Psychology', 'Project CE'),
('Sociology 105', 'Family Sociology', 'Project CF'),
('Anthropology 105', 'Cultural Evolution', 'Project CG'),
('Archeology 105', 'Mesoamerican Archaeology', 'Project CH'),
('Art History 105', 'European Art', 'Project CI'),
('Music Theory 105', 'Jazz Theory', 'Project CJ'),
('Philosophy 105', 'Logic', 'Project CK'),
('Statistics 105', 'Multivariate Analysis', 'Project CL');